### PR TITLE
Nmapxml input option

### PR DESCRIPTION
**Pull request by BastienFaure**
Hello !

I'd love to have this feature merged into master as Nmap XML output contain everything needed to identify SSL/TLS enabled services.

Broadly speaking, I iterate over each host and service in the XML file, and each time a service is SSL/TLS enabled, I add to the list of targets:
- the IP/port itself
- every hostname/port combination

Not sure we want to scan all targets, maybe just hostnames are enough, but it will possibly include PTR records as well.

Thoughts ?

### CODE REVIEW

**Comment by nabla-c0d3** [comment]
Hello and thanks for your contribution.

Your code looks good but libnmap does not seem to be maintained anymore and it doesn't support Python 3.7 and Python 3.8 (which the next version of SSLyze is going to support). Hence I can't add libnmap itself as a dependency.

**Comment by BastienFaure** [comment]
Hey !
Oh I see. Well I used libnmap for convenience, but I can also extract the information with direct XML parsing, the parsing will grow a bit but I can work on that if you want that feature merged :)
Let me know

**Comment by nabla-c0d3** [comment]
Sure - I will merge this feature if it doesn't add the libnmap dependency. Make sureto add a test that takes a sample XML file and validates that your code is able to parse it. Thanks!

**Comment by BastienFaure** [comment]
Hi @nabla-c0d3 

Just pushed a commit using lxml to extract SSL enabled services. Does lxml work for you ? I will add the tests and the dependencies once I got your approval for this :)

**Comment by nabla-c0d3** [comment]
Yeah lxml works! When you have it, also submitting a DNS hostname would be useful too. Thanks!

**Comment by bishopfaure** [comment]
Hey, sorry for the delay ! I've switched the depency to lxml and added hostname detection. Would those changes work for you ?
Thanks !

**Comment by BastienFaure** [comment]
Hey, sorry for the delay ! I've switched the dependency to lxml and added hostname detection. Would those changes work for you ?
Thanks !

**Comment by nabla-c0d3** [comment]
Thanks - it looks good. Can you add a test that does the following: it takes a sample NMAP XML file (you can commit it in the tests folder), runs your code on it, and ensures the right servers were detected. It will require you to move your parsing logic to a function.
Thanks!

**Pull request closed without merging**
