### PR TITLE
Updated OpenSslCipherSuitesPlugin to check cipher suite order preference

### PR DESCRIPTION
**Pull request by tykkz**
I think the requested feature in #120 is ready. `SSLyze` can now check whether the server has its own cipher order preference list or not :)

I have only modified `OpenSslCipherSuitesPlugin`, added test cases accordingly, and updated the XML schema to match the preference.

Thanks.

### CODE REVIEW

**Comment by nabla-c0d3** [comment]
Nice and thanks! Will look at it some time next week.

**Comment by nabla-c0d3** [comment]
It looks good! Please make the following changes and I will merge the PR:
* Switch the result's attribute from `cipher_order_pref` (which can be `server` or `client`) to `follows_client_cipher_suite_preference` (which can be `True` or `False`). It will make the result even simpler to process.
* Same thing for the XML output.
* If you have time (but no worries if not), please find a server that follows the client's order, and one that doesn't, and use them to have a test for each value. This will ensure your check fully works.

Thanks!

**Comment by tykkz** [comment]
I have done the changes that you have requested.

I selected `sogou.com` domain as test case by analyzing domains in `top100.txt` file. :)

**Comment by nabla-c0d3** [comment]
Thanks!

**Comment by nabla-c0d3** [comment]
FYI and just in case you have interested, I did some refactoring of some of my code and some of your code: https://github.com/nabla-c0d3/sslyze/commit/882f6e37a3ef6b0dd94411a2fb0d683125443df3 .

**Comment by tykkz** [comment]
I actually wanted to make similar changes but did not want to interfere extensively with the existing code base. It looks much clear now :)

**Pull request merged**
