### PR TITLE
Enable docker

### PR DESCRIPTION
**Pull request by circa10a**
Reopening with `slim` image:

I've created my own repo and docker image for your awesome app, but would prefer to see it stay with the original project.

This functionality alleviates common installation/usage problems with python versioning and package conflicts.

### CODE REVIEW

**Comment by nabla-c0d3** [comment]
Thanks!

**Comment by circa10a** [comment]
@nabla-c0d3 Don't forget to setup the automated build on docker hub! 😄

**Comment by nabla-c0d3** [comment]
Sounds good - how do I do this?

**Comment by circa10a** [comment]
@nabla-c0d3 
Here's a reference: https://docs.docker.com/docker-hub/builds/#link-to-a-hosted-repository-service

Basically just need to create an account on docker hub and point to the `sslyze` github repo

**Comment by nabla-c0d3** [comment]
Should be all set. Thanks for the help!

**Pull request merged**
