### PR TITLE
Added a plugin for RFC7465 checking

### PR DESCRIPTION
**Pull request by bluec0re**
According to RFC7465, RC4 is forbidden for TLS1.x.

### CODE REVIEW

**Comment by nabla-c0d3** [comment]
Thanks for the contribution. However PluginOpenSSLCipherSuites already gives us this info... why another plugin ?

**Comment by bluec0re** [comment]
The same applies to chrome_sha1 and certinfo, doesn't it? I found it more convenient for quick and automated checks.

**Comment by nabla-c0d3** [comment]
I agree it does apply to chrome_sha1, which will disappear as soon as there's a nice tool that can process the XML results and display them nicely. SSLyze already has too many command line options and I don't want to make it even more complicated.

**Comment by nabla-c0d3** [comment]
Duplicate of #111

**Pull request closed without merging**
