### PR TITLE
add HPKP support

### PR DESCRIPTION
**Pull request by azet**
This Plugin (largely copied off the HSTS one) checks if a HPKP header is set.

### CODE REVIEW

**Comment by tuftedocelot** [comment]
Should this actually verify the keys pinned instead of just reporting what the pins are present?

**Comment by azet** [comment]
@tuftedocelot 

Agreed. Will add in the next week or so (currently traveling).

**Comment by azet** [comment]
@tuftedocelot 

Had some time to take a look at that. To the best of my judgement this cannot be easily done with the current `nassl` lib as is. The problem really is parsing and converting of DER encoded certificate data for HPKP verification to work. For now I suggest just to check this field and export any value that has been set (this can be manually verified with e.g. a script).

**Comment by nabla-c0d3** [comment]
I added this functionality in 0.14.0.

**Pull request closed without merging**
