### PR TITLE
Added a new plugin to detect the use of TLS Server Name Indication (SNI)

### PR DESCRIPTION
**Pull request by okoeroo**
It will compare the fingerprints of the EEC/leaf certificates of a chain. If there is a difference noticed based on toggling the SNI on or off, this will conclude if SNI was used or a different verdict.

### CODE REVIEW

**Comment by nabla-c0d3** [comment]
Thanks for the contribution. What is the use case for this ? As mentioned in your code, the server may be sending back the same cert regardless of SNI, so I'm not sure there's value in checking for this. Also knowing that a server uses SNI doesn't seem to be very useful either, or is it ?
Thanks!

**Comment by okoeroo** [comment]
I work for a telco with older and newer systems, SNI configured and not. SNI could be misconfigured, but to understand this might be the case a scan result like this could help. Also, we're busy with vulnerability scanners and the scanners can do a check by IP-address pretty well, but when Virtual Hosting on SSL is enabled this is a must-scan-by-hostname fix case. I'd like to catch those cases explicitly with this plugin.

**Comment by konklone** [comment]
Tracking whether SNI is required by a site is very helpful, especially when looking at changes in a dataset over time. This is something SSL Labs provides.

**Comment by nabla-c0d3** [comment]
There does not seem to be a way to check for SNI without prior knowledge of the names supported by the server (http://serverfault.com/questions/506177/how-can-i-detect-if-a-server-is-using-sni-for-https ). Providing a fake name may or may not work. Hence, this check is too unreliable.

**Pull request closed without merging**
